version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: ./api
    ports:
      - 3001:3001
  nginx:
    image: nginx
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
